Repository Dev-Race/DevRace-frontend, pull requests merged in 2024-05, with the labels that each got.

#2 [#1] Setting: 프로젝트 초기 세팅
  .prettierrc
  README.md
  package-lock.json
  package.json
  public/index.html
  public/logo192.png
  public/logo512.png
  public/robots.txt
  src/App.js
  src/router/Router.jsx
Labels: ⚙️ Setting

#4 [#3] Feat: 디자인 시스템 구현
  src/component/common/Button.jsx
  src/component/common/DropDown.jsx
  src/component/common/Input.jsx
  src/component/common/Modal.jsx
  src/component/common/Pagination.jsx
  src/component/common/Push.jsx
  src/component/common/RankList.jsx
  src/component/common/Toggle.jsx
  src/component/layout/Footer.jsx
  src/component/layout/Header.jsx
  src/icons/arrow_down_white.svg
  src/icons/basic_small_image.svg
  src/icons/check_green.svg
  src/icons/checked_icon.svg
  src/icons/dark_mode.svg
  src/icons/default_profile.svg
  src/icons/down_arrow.svg
  src/icons/error_icon.svg
  src/icons/exit_white.svg
  src/icons/fail_dark.svg
  src/icons/fail_light.svg
  src/icons/git_icon.svg
  src/icons/google_icon.svg
  src/icons/group_icon.svg
  src/icons/light_mode.svg
  src/icons/logo_dark.svg
  src/icons/logo_icon_dark.svg
  src/icons/logo_icon_light.svg
  src/icons/logo_light.svg
  src/icons/modal_close.svg
  src/icons/next_page.svg
  src/icons/no_black.svg
  src/icons/people_dark.svg
  src/icons/people_light.svg
  src/icons/plus_icon.svg
  src/icons/prev_page.svg
  src/icons/profile_edited.svg
  src/icons/reset_icon.svg
  src/icons/search.svg
  src/icons/send_icon.svg
  src/icons/setting.svg
  src/icons/success_dark.svg
  src/icons/success_light.svg
  src/icons/twinkle_icon.svg
  src/icons/wating_icon.svg
  src/icons/yes_black.svg
  src/pages/TestPage.jsx
  src/router/Router.jsx
  src/styles/_theme.scss
  src/styles/common/Button.scss
  src/styles/common/DropDown.scss
  src/styles/common/Input.scss
  src/styles/common/Modal.scss
  src/styles/common/Pagination.scss
  src/styles/common/Push.scss
  src/styles/common/RankList.scss
  src/styles/common/Toggle.scss
  src/styles/layout/Footer.scss
  src/styles/layout/Header.scss
  yarn.lock
Labels: ✨ Feat

#8 [#7] Feat: 회원가입 및 로그인
  .gitignore
  public/index.html
  src/apis/Api.jsx
  src/apis/register.jsx
  src/component/common/Button.jsx
  src/component/common/Modal.jsx
  src/component/layout/Footer.jsx
  src/component/layout/Header.jsx
  src/pages/InfoPage.jsx
  src/pages/LoginPage.jsx
  src/reducers/index.jsx
  src/reducers/member/member.jsx
  src/router/Router.jsx
  src/styles/common/Button.scss
  src/styles/common/Modal.scss
  src/styles/layout/Footer.scss
  src/styles/layout/Header.scss
  src/styles/pages/InfoPage.scss
  src/styles/pages/LoginPage.scss
Labels: ✨ Feat

#10 [#9] Refactor: 로그인 및 회원가입 리팩토링
  src/apis/register.jsx
  src/pages/InfoPage.jsx
  src/styles/pages/InfoPage.scss
Labels: ♻️ Refactor

#16 [#15] Refactor: axios Instance 수정
  src/apis/Api.jsx
  src/component/layout/Header.jsx
  src/pages/MainPage.jsx
Labels: ♻️ Refactor

#20 [#17] Refactor: 회원가입 비지니스 로직 리팩토링
  src/apis/register.jsx
  src/component/common/Input.jsx
  src/pages/InfoPage.jsx
Labels: ♻️ Refactor

#22 [#21] Feat: 문제 생성 페이지 axios 연동
  src/apis/createProblem.jsx
  src/apis/member.jsx
  src/pages/CreateRoomPage.jsx
  src/pages/InfoPage.jsx
  src/pages/MainPage.jsx
  src/styles/layout/Header.scss
Labels: ✨ Feat

#24 [#23] Feat: 실시간 입장 페이지 구현
  src/apis/createProblem.jsx
  src/apis/member.jsx
  src/apis/room.jsx
  src/assets/icons/roomManager.svg
  src/component/common/Push.jsx
  src/component/layout/Header.jsx
  src/pages/CreateRoomPage.jsx
  src/pages/InfoPage.jsx
  src/pages/MainPage.jsx
  src/pages/RedirectPage.jsx
  src/pages/SolvePage.jsx
  src/pages/WaitPage.jsx
  src/router/Router.jsx
  src/styles/common/Push.scss
  src/styles/pages/CreateRoomPage.scss
  src/styles/pages/WaitPage.scss
Labels: ✨ Feat

#27 [Chore] 회원 가입 및 동시 입장 수정
  src/apis/register.jsx
  src/pages/WaitPage.jsx
Labels: 🔧 Chore
