Repository Dev-Race/DevRace-frontend, pull requests merged in 2024-06, with the labels that each got.

#30 [#29] Feat: 문제 풀이 페이지 axios 구현
  src/apis/compileCode.jsx
  src/apis/problem.jsx
  src/component/editor/CodeEditor.jsx
  src/component/editor/Output.jsx
  src/component/layout/Footer.jsx
  src/component/layout/Header.jsx
  src/pages/SolvePage.jsx
  src/styles/pages/SolvePage.scss
Labels: ✨ Feat

#32 [#31] Feat: 문제 풀이 페이지 비지니스 로직 구현
  package-lock.json
  src/apis/problem.jsx
  src/component/chat/ChatComponent.jsx
  src/component/common/Input.jsx
  src/component/common/Toggle.jsx
  src/component/layout/Header.jsx
  src/pages/SolvePage.jsx
  src/styles/components/ChatComponent.scss
  yarn.lock
Labels: ✨ Feat

#38 [#37] Feat: Modal 관련 비지니스 로직 작성
  src/apis/problem.jsx
  src/component/chat/ChatComponent.jsx
  src/component/common/Modal.jsx
  src/component/common/RankList.jsx
  src/pages/MainPage.jsx
  src/pages/RedirectPage.jsx
  src/pages/SolvePage.jsx
  src/styles/common/RankList.scss
Labels: ✨ Feat

#48 [#47] Refacotr: 코드 리팩토링
  src/component/chat/ChatComponent.jsx
  src/component/common/Modal.jsx
  src/pages/EditPage.jsx
  src/pages/MyPage.jsx
  src/styles/components/ChatComponent.scss
  src/styles/layout/Header.scss
  src/styles/pages/MyPage.scss
Labels: ♻️ Refactor

#54 [#53] Refactor: 뒤로가기 막기 및 헤더 버튼 커서 변경
  package-lock.json
  package.json
  public/index.html
  src/component/layout/Header.jsx
  src/pages/InfoPage.jsx
  src/pages/MyPage.jsx
  src/styles/layout/Header.scss
  src/styles/pages/MyPage.scss
  yarn.lock
Labels: ♻️ Refactor

#56 [#53] Refactor: 채팅 컴포넌트 수정 및 헤더 아이콘 수정
  src/component/chat/ChatComponent.jsx
  src/component/layout/Header.jsx
  src/pages/SolvePage.jsx
  src/pages/WaitPage.jsx
  src/router/Router.jsx
  src/styles/components/ChatComponent.scss
Labels: ♻️ Refactor

#69 [#68] Fix: 문제풀이 페이지 오류 해결
  src/apis/problem.jsx
  src/component/chat/ChatComponent.jsx
  src/component/common/Input.jsx
  src/component/editor/CodeEditor.jsx
  src/pages/MyCodePage.jsx
  src/pages/SolvePage.jsx
  src/styles/common/RankList.scss
Labels: 🐛 Fix
